pluginManagement {
    repositories {
        // Adding githubPackages{} below replaces the implicit default repo list,
        // so the Plugin Portal needs to be re-added explicitly.
        gradlePluginPortal()
    }
}

plugins {
    id 'io.github.duckasteroid.github-packages-settings' version '0.2.0'
}

githubPackages {
    owner = "duckAsteroid"
    repository = "gradle-convention-plugin"
}

rootProject.name = 'opengl-jogl-template'
include 'core', 'experiments', 'application'

