package com.asteroid.duck.opengl.util.resources.buffer.vbo;

import com.asteroid.duck.opengl.util.RenderContext;
import com.asteroid.duck.opengl.util.resources.Resource;
import com.asteroid.duck.opengl.util.resources.buffer.BufferDrawMode;
import com.asteroid.duck.opengl.util.resources.buffer.UpdateHint;
import com.asteroid.duck.opengl.util.resources.buffer.VertexArrayObject;
import com.asteroid.duck.opengl.util.resources.shader.ShaderProgram;
import org.lwjgl.system.MemoryUtil;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.ByteBuffer;
import java.util.*;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

import static org.lwjgl.opengl.GL15.*;
import static org.lwjgl.opengl.GL20.*;

/**
 * CPU/GPU-backed vertex data store owned by a {@link VertexArrayObject}.
 *
 * <p>This class keeps a native CPU-side {@link ByteBuffer} copy of vertex data and uploads that data
 * to an OpenGL array buffer object (VBO). The per-vertex layout is described by
 * {@link VertexDataStructure}, which is made up of ordered {@link VertexElement}s.</p>
 *
 * <p>Typical lifecycle:</p>
 * <ol>
 *   <li>Create with an owner VAO, structure, and fixed vertex capacity.</li>
 *   <li>Call {@link #init(RenderContext)} once in an active OpenGL context.</li>
 *   <li>Populate/modify CPU-side data using {@link #set(int, Map)}, {@link #set(int, Object...)},
 *       or {@link #setElement(int, VertexElement, Object)}.</li>
 *   <li>Upload CPU-side data to GPU with {@link #update(UpdateHint)} (or during init).</li>
 *   <li>Configure attribute pointers with {@link #setup(ShaderProgram)} for a shader program.</li>
 *   <li>Dispose native and GL resources with {@link #dispose()}.</li>
 * </ol>
 *
 * <p>Threading: this class is not thread-safe; use it from the render/OpenGL thread.</p>
 */
public class VertexBufferObject extends AbstractList<Map<VertexElement, ?>> implements Resource {

	private static final Logger log = LoggerFactory.getLogger(VertexBufferObject.class);

	/** The VAO that owns this VBO. */
	private final VertexArrayObject owner;

    private static final byte ZERO_BYTE = 0;
	/**
	 * This defines the order of the elements for each vertex.
	 */
	private final VertexDataStructure vertexDataStructure;
	/**
	 * The maximum number of vertices that can be stored in the buffer.
	 * Each vertice will have a set of data elements associated as described by the structure.
	 */
	private final int capacity;
	/**
	 * A memory buffer that contains the raw vertex data
	 */
	private ByteBuffer memBuffer = null;

	/** OpenGL buffer object id generated by {@code glGenBuffers}. */
	private int vbo;
	/**
	 * The update hint for the buffer.
	 * This defines how the data will be used and how it should be optimised.
	 * Defaults to {@link UpdateHint#STATIC}.
	 */
	private UpdateHint updateHint = UpdateHint.STATIC;
	/**
	 * The draw mode to use when rendering the vertex data.
	 * Defaults to {@link BufferDrawMode#TRIANGLES}.
	 */
	private BufferDrawMode drawMode = BufferDrawMode.TRIANGLES;
	/**
	 * Creates a fixed-capacity VBO model.
	 *
	 * @param owner owning VAO that this VBO is attached to
	 * @param structure vertex layout definition used for serialization and offsets
	 * @param capacity maximum number of vertices storable in CPU/GPU buffer
	 * @throws NullPointerException if {@code owner} or {@code structure} is null
	 * @throws IllegalArgumentException if {@code capacity <= 0}
	 */
	public VertexBufferObject(VertexArrayObject owner, VertexDataStructure structure, int capacity) {
		Objects.requireNonNull(owner);
		this.owner = owner;
		Objects.requireNonNull(structure);
		if (capacity <= 0) {
			throw new IllegalArgumentException("Initial size must be greater than zero");
		}
		this.vertexDataStructure = structure;
		this.capacity = capacity;
	}

	/**
	 * Returns the owning VAO for this VBO.
	 *
	 * @return owner VAO
	 */
	public VertexArrayObject getOwner() {
		return owner;
	}

	/**
	 * Get the vertex data structure that defines the data for each vertex.
	 * @return the vertex data structure
	 */
	public VertexDataStructure getStructure() {
		return vertexDataStructure;
	}

	/**
	 * Returns the current upload usage hint.
	 *
	 * @return OpenGL usage hint used by buffer uploads
	 */
	public UpdateHint getUpdateHint() {
		return updateHint;
	}

	/**
	 * Sets the default upload usage hint for future uploads.
	 *
	 * @param updateHint usage hint to use; may be null only if caller later supplies a hint to
	 *                   {@link #update(UpdateHint)}
	 */
	public void setUpdateHint(UpdateHint updateHint) {
		this.updateHint = updateHint;
	}

	/**
	 * Returns the primitive draw mode associated with this VBO.
	 *
	 * @return draw mode metadata for this VBO
	 */
	public BufferDrawMode getDrawMode() {
		return drawMode;
	}

	/**
	 * Sets the primitive draw mode metadata associated with this VBO.
	 *
	 * <p>Note: draw calls are performed by the owning VAO, which may use its own draw mode.</p>
	 *
	 * @param drawMode primitive mode
	 */
	public void setDrawMode(BufferDrawMode drawMode) {
		this.drawMode = drawMode;
	}

	/**
	 * Returns an iterable over the raw CPU-side vertex bytes.
	 *
	 * @return iterable byte view of the backing native buffer
	 * @see #duplicate(ByteBuffer)
	 */
	public Iterable<Byte> bytes() {
		return () -> new Iterator<>() {
			private final ByteBuffer copy = duplicate(memBuffer);

			@Override
			public boolean hasNext() {
				return memBuffer.hasRemaining();
			}

			@Override
			public Byte next() {
				return memBuffer.get();
			}
		};
	}

	/**
	 * Returns a sequential stream over the raw CPU-side vertex bytes.
	 *
	 * @return byte stream for inspection/debugging
	 */
	public Stream<Byte> byteStream() {
		return StreamSupport.stream(bytes().spliterator(), false);
	}
	/**
	 * Like {@link ByteBuffer#duplicate()} but keeps the byte order!!
	 * @param original the byte buffer to copy
	 * @return the copy (same content, new pointers)
	 */
	private static ByteBuffer duplicate(ByteBuffer original) {
		ByteBuffer copy = original.duplicate();
		copy.order(original.order());
		return copy;
	}

	/**
	 * Returns total vertex capacity (not current "used" count).
	 *
	 * @return number of vertex slots in the backing buffer
	 */
	@Override
	public int size() {
		return memBuffer.capacity() / vertexDataStructure.size();
	}

	/**
	 * Get the raw underlying memory that contains the vertex data as a ByteBuffer.
	 * @return the memory buffer
	 */
	public ByteBuffer memBuffer() {
		return memBuffer;
	}

	/**
	 * Allocates and initializes the OpenGL VBO and CPU-side native buffer.
	 *
	 * <p>This binds the owner VAO, creates the GL array buffer, allocates native memory,
	 * and uploads initial data according to {@link #updateHint}.</p>
	 *
	 * @param ctx active render context with current OpenGL context
	 */
	public void init(RenderContext ctx) {
		owner.bind(ctx);
		// Create a VBO and bind it
		vbo = glGenBuffers();
		glBindBuffer(GL_ARRAY_BUFFER, vbo);
		createBuffer();
		// initialise the buffer with the memory buffer
		glBufferData(GL_ARRAY_BUFFER, memBuffer, updateHint.openGlCode());
	}

	/**
	 * Configures vertex attribute pointers for a shader program.
	 *
	 * <p>Each {@link VertexElement#name()} is resolved as a shader attribute location and then mapped
	 * using this VBO's structure stride/offset metadata.</p>
	 *
	 * <p>This method assumes the owning VAO/VBO are currently bound and the shader exposes matching
	 * attribute definitions.</p>
	 *
	 * @param shader shader program whose attribute names match the vertex structure
	 */
	public void setup(ShaderProgram shader) {
		// FIXME check the shader is compatible with the vertex data structure
		for(VertexElement element : vertexDataStructure) {
			int position = shader.getAttributeLocation(element.name());
			log.debug("Setting up vertex attribute '{}' at position {} in {}", element.name(), position, shader.shortDebugName());
			setVertexAttribPointer(
							position,
							element.type().dimensions(),
							element.type().glType(),
							false,
							vertexDataStructure.size(),
							vertexDataStructure.getOffset(element));
		}
	}

	/**
	 * Defines and enables one vertex attribute pointer in the current VAO.
	 *
	 * <p>Calls {@link org.lwjgl.opengl.GL20#glVertexAttribPointer(int, int, int, boolean, int, long)}
	 * and {@link org.lwjgl.opengl.GL20#glEnableVertexAttribArray(int)}.</p>
	 *
	 * @param position attribute location in shader
	 * @param size number of components for this attribute
	 * @param type OpenGL scalar type code (for example {@code GL_FLOAT})
	 * @param normalized whether fixed-point data should be normalized by GL
	 * @param stride byte stride between consecutive vertex records
	 * @param pointer byte offset of this attribute in each record
	 */
	protected void setVertexAttribPointer(int position, int size, int type, boolean normalized, int stride, long pointer) {
		glVertexAttribPointer(position, size, type, normalized, stride, pointer);
		glEnableVertexAttribArray(position);
	}

	/**
	 * Allocates native CPU-side memory for all vertex slots.
	 *
	 * <p>Allocated size is {@code capacity * structure.size()} bytes and must be released in
	 * {@link #dispose()}.</p>
	 */
	public void createBuffer() {
		// create a memory buffer of the initial size
		this.memBuffer = MemoryUtil.memAlloc(capacity * vertexDataStructure.size());
	}


	/**
	 * Reads one vertex record from the CPU-side buffer.
	 *
	 * @param index vertex index to read
	 * @return immutable map of all element values for that vertex
	 */
	@Override
	public Map<VertexElement, ?> get(int index) {
		ByteBuffer readCopy = duplicate(memBuffer);
		readCopy.position(index * vertexDataStructure.size());
		Map<VertexElement, Object> result = new HashMap<>();
		for(VertexElement element : vertexDataStructure) {
			Object object = element.type().deserializeRaw(readCopy);
			result.put(element, object);
		}
		return Collections.unmodifiableMap(result);
	}

	/**
	 * Reads a single element value from one vertex record.
	 *
	 * @param index vertex index
	 * @param element element descriptor to read
	 * @return decoded element value
	 */
	public Object getElement(int index, VertexElement element) {
		ByteBuffer readCopy = duplicate(memBuffer);
		long elementOffset = vertexDataStructure.getOffset(element);
		readCopy.position((int) ((index * vertexDataStructure.size()) + elementOffset));
		return element.type().deserializeRaw(readCopy);
	}

	/**
	 * Writes a full vertex record into the CPU-side buffer.
	 *
	 * @param index vertex index to overwrite
	 * @param vertexData full element map matching {@link #vertexDataStructure}
	 * @return the supplied map
	 */
	@Override
	public Map<VertexElement, ?> set(int index, Map<VertexElement, ?> vertexData) {
		vertexDataStructure.checkStructure(vertexData);
		ByteBuffer writeCopy = duplicate(memBuffer);
		writeCopy.position(index * vertexDataStructure.size());
		for(VertexElement element : vertexDataStructure) {
			Object object = vertexData.get(element);
			VertexElementType<?> type = element.type();
			type.serializeRaw(object, writeCopy);
		}
		return vertexData;
	}

	/**
	 * Convenience overload of {@link #set(int, Map)} using positional values.
	 *
	 * @param index vertex index to overwrite
	 * @param data element values in structure order
	 * @return the created element map that was written
	 */
	public Map<VertexElement, ?> set(int index, Object ... data) {
		return set(index, vertexDataStructure.asMap(data));
	}

	/**
	 * Writes a single element inside one vertex record.
	 *
	 * @param index vertex index to modify
	 * @param element element descriptor to write
	 * @param data value to serialize for that element
	 */
	public void setElement(int index, VertexElement element, Object data) {
		ByteBuffer writeCopy = duplicate(memBuffer);
		long elementOffset = vertexDataStructure.getOffset(element);
		writeCopy.position((int) ((index * vertexDataStructure.size()) + elementOffset));
		VertexElementType<?> type = element.type();
		type.serializeRaw(data, writeCopy);
	}

	/**
	 * Zeros one vertex record in the CPU-side buffer.
	 *
	 * @param index vertex index to clear
	 * @return previously stored vertex data
	 */
	@Override
	public Map<VertexElement, ?> remove(int index) {
		Map<VertexElement, ?> current = get(index);
		ByteBuffer writeCopy = duplicate(memBuffer);
		writeCopy.position(index * vertexDataStructure.size());
		for (int i = 0; i < vertexDataStructure.size(); i++) {
			writeCopy.put(ZERO_BYTE);
		}
		return current;
	}

	/**
	 * Uploads CPU-side vertex bytes to the bound GL array buffer.
	 *
	 * <p>If {@code hint} is null, {@link UpdateHint#STATIC} is used for this upload call.</p>
	 *
	 * @param hint usage hint for this upload invocation
	 */
	public void update(UpdateHint hint) {
		glBindBuffer(GL_ARRAY_BUFFER, vbo);
		if (hint == null) {
			hint = UpdateHint.STATIC;
		}
		glBufferData(GL_ARRAY_BUFFER, memBuffer, hint.openGlCode());
	}


	/**
	 * Releases GL and native resources for this VBO.
	 *
	 * <p>After disposal, this instance should not be used again.</p>
	 */
	@Override
	public void dispose() {
		glDeleteBuffers(vbo);
		MemoryUtil.memFree(memBuffer);
		memBuffer = null;
	}
}
